fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    docker: "https://github.com/puppetlabs/puppetlabs-docker.git"
    concat:
      repo: https://github.com/syseleven/puppetlabs-concat.git
      branch: deferred-function
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
